Repository victorfrye/microsoftgraveyard, pull requests merged in 2024-01, with the labels that each got.

#36 feat(aot): run aot compilation and test page load
  src/Client/Client.csproj
Labels: enhancement

#37 feat(corpses): add nine additional dead products from ms history
  src/Client/wwwroot/data/corpses.json
Labels: new dead product

#40 feat: update content components and meta tags
  src/Client/Components/Content/Graveyard.razor
  src/Client/Components/Content/Graveyard.razor.css
  src/Client/Components/Content/SocialButtons.razor
  src/Client/Components/Content/SocialButtons.razor.css
  src/Client/Components/Content/Socials.razor
  src/Client/Components/Layouts/FooterLayout.razor
  src/Client/Models/Corpse.cs
  src/Client/Models/Social.cs
  src/Client/wwwroot/data/corpses.json
  src/Client/wwwroot/images/coffin.svg
  src/Client/wwwroot/images/home.svg
  src/Client/wwwroot/images/skull.svg
  src/Client/wwwroot/index.html
  src/Client/wwwroot/styles/app.css
Labels: enhancement, new dead product

#45 Adjust threads link
  src/Client/Components/Layouts/FooterLayout.razor
Labels: bug

#48 feat(corpses): add sunrise and foxpro
  src/Client/wwwroot/data/corpses.json
Labels: .NET, new dead product

#54 feat(corpses): add the remainder of my initial list
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
  README.md
  src/Client/wwwroot/data/corpses.json
Labels: documentation, new dead product

#55 chore: add devcontainer for gh codespaces support
  .devcontainer/devcontainer.json
Labels: enhancement

#58 feat(corpses): add headstone for pixelsense
  src/Client/wwwroot/data/corpses.json
Labels: new dead product
